# Timezone to format all dates in
timezone: "America/New_York"

chain_cybersec: ["github_cybersec", "mastodon_cybersec", "script_blog"]

github_cybersec:
  # The GitHub repository to put blog posts in
  GITHUB_USERNAME: "p0lyw0lf"
  GITHUB_REPO: "website"
  GITHUB_BRANCH: "main"
  GITHUB_OUTPUT_DIR: "src/content/cybersec"
  # The template to use
  template: "github_cybersec.md.j2"

mastodon_cybersec:
  template: "mastodon_cybersec.txt.j2"

chain_blog: ["github_blog", "script_blog", "mastodon_blog", "bluesky_blog", "github_blog", "script_blog"]

github_blog:
  GITHUB_USERNAME: "p0lyw0lf"
  GITHUB_REPO: "website"
  GITHUB_BRANCH: "main"
  GITHUB_OUTPUT_DIR: "src/content/blog"
  template: "github_blog.md.j2"

script_blog:
  path: "scripts/publish_blog.sh"

mastodon_blog:
  template: "mastodon_blog.txt.j2"
  add_tags: 1

bluesky_blog:
  template: "bluesky_blog.md.j2"
  add_tags: 1

outputs:
  bot: "chain_cybersec"
  server: "chain_blog"

TESTING: true
