# Timezone to format all dates in
timezone="America/New_York"

# Discord bot information, like the server and user it should respond to
DISCORD_GUILD_ID=0
DISCORD_OWNER_ID=0

# Discord access token
DISCORD_TOKEN=""

# Repository information, for where to place completed posts
GITHUB_USERNAME="p0lyw0lf"
GITHUB_REPO="website"
GITHUB_BRANCH="main-test"
GITHUB_OUTPUT_DIR="src/pages/cybersec"

# Personal Access Token
GITHUB_TOKEN=""

# Mastodon information
MASTODON_BASE_URL="https://infosec.exchange"

# "Your Access Token"
MASTODON_TOKEN=""
