# Timezone to format all dates in
timezone="America/New_York"

# For the discord bot
# Discord bot information, like the server and user it should respond to
DISCORD_GUILD_ID=0
DISCORD_OWNER_ID=0

# Discord access token
DISCORD_TOKEN=""

# For the server
SERVER_SECRET=""

# For static file upload
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION_NAME="us-east-1"
AWS_BUCKET_NAME="static.wolfgirl.dev"

[server.users]
polywolf="password"

[github]
# Personal Access Token
GITHUB_TOKEN=""

[mastodon]
# Mastodon information
MASTODON_BASE_URL="https://infosec.exchange"
# "Your Access Token"
MASTODON_TOKEN=""

[bluesky]
BLUESKY_HOMESERVER="https://girl.technology"
BLUESKY_USERNAME="wolf.girl.technology"
BLUESKY_PASSWORD=""
