[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "poster"
version = "0.1.1"
dependencies = [
  "Mastodon.py",
  "PyYAML",
  "atproto",
  "githubkit[auth-app]",
  "jinja2",
  "mistletoe",
  "python-frontmatter",
  "tzdata",
]
