[github_cybersec]
# Repository information, for where to place completed posts
GITHUB_USERNAME="p0lyw0lf"
GITHUB_REPO="website"
GITHUB_BRANCH="main"
GITHUB_OUTPUT_DIR="src/content/cybersec"
# What template to use
template="github_cybersec.md.j2"

[github_blog]
GITHUB_USERNAME="p0lyw0lf"
GITHUB_REPO="website"
GITHUB_BRANCH="main"
GITHUB_OUTPUT_DIR="src/content/blog"
template="github_blog.md.j2"

[mastodon_cybersec]
template="mastodon_cybersec.txt.j2"

[mastodon_blog]
template="mastodon_blog.txt.j2"
add_tags=1

[bluesky_blog]
template="bluesky_blog.md.j2"
add_tags=1

[outputs]
bot = ["github_cybersec", "mastodon_cybersec"]
server = ["mastodon_blog", "bluesky_blog", "github_blog"]

TESTING=true
