# Timezone to format all dates in
timezone="America/New_York"

# Repository information, for where to place completed posts
GITHUB_USERNAME="p0lyw0lf"
GITHUB_REPO="website"
GITHUB_BRANCH="main"
GITHUB_OUTPUT_DIR="src/pages/cybersec"

# Personal Access Token
GITHUB_TOKEN=""
